---
- name: Deploy code
  copy: 
    src: "../../../../{{ item }}"
    dest: "/webapps/vcl/vcl-dashboard/"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
  with_items:
    - requirements.txt
    - vcl
    - manage.py

- name: Make manage.py executable
  file: path=/webapps/vcl/vcl-dashboard/manage.py mode=a+rx
