---

- { import_tasks: apt.yml,          tags: ["packages"]  }
- { import_tasks: users.yml,        tags: ["users"]     }
- { import_tasks: deploy.yml,       tags: ["deploy"]    }

- { include: virtualenv.yml,        tags: ["virtualenv"]}
- { include: mysql.yml,             tags: ["mysql"]     }
- { include: django.yml,            tags: ["django"]    }

- name: copy boto credentials for AWS API client
  template: src=boto.cfg.j2 dest=/etc/boto.cfg

- name: copy instance key
  copy: content={{ amazon_instance_key }} dest=/instance_key.pem mode=0400

# Supervisor setup
- name: Create the SystemD config file
  template: src=systemd.service.j2
            dest=/etc/systemd/system/{{ application_name }}.service
            backup=no

# - name: Re-read the Supervisor config files
#   command: systemctl daemon-reload

- name: Restart application
  service: name={{ application_name }} state=restarted

- name: Ensure that the application file permissions are set properly
  file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
  notify: restart application
  tags: deploy

- include: nginx.yml
  tags: nginx
