---

- name: Copy the SSL certificate to the remote server
  copy: content="{{ ssl_crt }}" dest={{ ssl_dest_dir }}/{{ application_name }}.crt
  notify: reload nginx

- name: Copy the SSL private key to the remote server
  copy: content="{{ ssl_key }}" dest={{ ssl_dest_dir }}/{{ application_name }}.key
  notify: reload nginx

- name: Create the Nginx configuration file
  template: src=nginx_site_config.j2 dest=/etc/nginx/sites-available/{{ application_name }}.conf backup=yes
  notify: reload nginx

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Ensure that the application site is enabled
  file: state=link src=/etc/nginx/sites-available/{{ application_name }}.conf dest=/etc/nginx/sites-enabled/{{ application_name }}.conf
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
